namespace Simulator.Runtime.Input;

public enum GameKey
{
    None = 0,
    Enter,
    Escape,
    Tab,
    Space,
    Backspace,
    Delete,
    PageUp,
    PageDown,
    LeftShift,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    A,
    B,
    C,
    D,
    E,
    F,
    H,
    I,
    J,
    K,
    L,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    V,
    W,
    X,
    Z,
    D0,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,
    NumPad0,
    NumPad1,
    NumPad2,
    NumPad3,
    NumPad4,
    NumPad5,
    NumPad6,
    NumPad7,
    NumPad8,
    NumPad9,
    NumPadDecimal,
    NumPadSubtract,
    Oem1,
    OemPeriod,
    OemMinus,
    OemQuestion,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
}

public enum GameMouseButton
{
    None = 0,
    Left,
    Right,
    Middle,
    Button4,
    Button5,
}

public readonly record struct GamePointerState(
    double X,
    double Y,
    double DeltaX,
    double DeltaY,
    double WheelDelta,
    bool CursorCaptured);

public sealed record GameInputSnapshot(
    long Frame,
    double TimeSec,
    IReadOnlySet<GameKey> DownKeys,
    IReadOnlySet<GameKey> PressedKeys,
    IReadOnlySet<GameKey> ReleasedKeys,
    IReadOnlySet<GameMouseButton> DownMouseButtons,
    IReadOnlySet<GameMouseButton> PressedMouseButtons,
    IReadOnlySet<GameMouseButton> ReleasedMouseButtons,
    GamePointerState Pointer)
{
    public static GameInputSnapshot Empty { get; } = new(
        0,
        0.0,
        new HashSet<GameKey>(),
        new HashSet<GameKey>(),
        new HashSet<GameKey>(),
        new HashSet<GameMouseButton>(),
        new HashSet<GameMouseButton>(),
        new HashSet<GameMouseButton>(),
        new GamePointerState(0, 0, 0, 0, 0, CursorCaptured: false));
}
